name: Docker Build Test

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-wordpress-image .

    - name: Run a container from the built image (optional)
      run: docker run --name test-container -d my-wordpress-image

    - name: Check if the container is running (optional)
      run: docker ps | grep test-container

    - name: Clean up (optional)
      run: docker stop test-container && docker rm test-container
